
card_set = {

    "Bouftou noir": "fighter",
    "Bouftou blanc": "fighter",
    "Bouftou céleste": "fighter",
    "Bouftou de guerre": "fighter",
    "Bouftou primitif": "fighter",
    "Boufmouth": "fighter",
    "Royalmouth": "fighter",
    "Tofukaz": "fighter",
    "Tofu mélanique": "fighter",
    "Tofu royal": "fighter",
    "Tofu ventripotent": "fighter",

    "Sanglier Porcass": "fighter",
    "Berger Porcass": "fighter",
    "Chevaucheur de Porcass": "fighter",
    "Samurai Porcass": "fighter",
    "Berserker Porcass": "fighter",
    "Flammetin": "fighter",
    "Tortue de lave": "fighter",
    "Élémentaire de lave": "fighter",
    "Acolyte de la souffrance": "fighter",
    "Sergent cruel": "fighter",
    "Singe féroce": "fighter",
    "Gobelin malade": "fighter",
    "Maitre blessé": "fighter",
    "Chargeur orc": "fighter",
    "Champion orc": "fighter",
    "Le Découpeur": "fighter",
    "Ogre glouton": "fighter",

    "Écuyer": "fighter",
    "Porte bouclier": "fighter",
    "Guetteur d'argent": "fighter",
    "Garde antique": "fighter",
    "Robot blindé": "fighter",
    "Luminotron": "fighter",
    "Engin de guerre": "fighter",
    "Robot de soin": "fighter",
    "Ziliax": "fighter",
    "Rejeton de lumière": "fighter",
    "Pacificateur": "fighter",
    "Silencieux": "fighter",
    "Chevalier gemme": "fighter",
    "Cavalier d'argent": "fighter",
    "Entraineur": "fighter",
    "Archer d'élite": "fighter",

    "Archère elf": "fighter",
    "Lutin des bois": "fighter",
    "Papillon enchanté": "fighter",
    "Sylvenier": "fighter",
    "Druide du sabre": "fighter",
    "Elf de guerre": "fighter",
    "Dryade": "fighter",
    "Satyre mystique": "fighter",
    "Golem ancien": "fighter",
    "Gardien du bosquet": "fighter",
    "Bête de la griffe": "fighter",
    "Combattant sauvage": "fighter",
    "Gardienne des bois": "fighter",
    "Ancien de la foret": "fighter",
    "Bastiosaure": "fighter",
    "Drake emeraude": "fighter",
    "Protecteur runique": "fighter",
    "Archidruide": "fighter",
    "Maitresse de la ménagerie": "fighter",

    "Boucanier": "fighter",
    "Matelot des mers": "fighter",
    "Forban": "fighter",
    "Vigie pirate": "fighter",
    "Capitaine pirate": "fighter",
    "Corsaire furtif": "fighter",
    "Manieur de sabre": "fighter",
    "Face de poulpe": "fighter",
    "Brigande du navire": "fighter",
    "Capitaine double crochet": "fighter",
    "Jeteur d'encre": "fighter",

    "Explorateur téméraire": "fighter",
    "Zapomatic": "fighter",
    "Élémentaire de poussière": "fighter",
    "Dragon d'argent": "fighter",
    "Lion du désert": "fighter",
    "Murozong": "fighter",
    "Grand dragon d'or": "fighter",
    "Garde lumière": "fighter",
    "Roi de Fondor": "fighter",
    "Géode lumineuse": "fighter",
    "Prêtresse corrompue": "fighter",
    "Clerc du royaume": "fighter",
    "Dragon cactus": "fighter",
    "Grande prêtresse Ninlil": "fighter",

    "Alchimiste des étoiles": "fighter",
    "Malygos": "fighter",
    "Pillard gobelin": "fighter",
    "Gobelin effrayé": "fighter",
    "Sisu, gardienne céleste": "fighter",
    "Commandant du désert": "fighter",
    "Bricoleur": "fighter",
    "Robot barbier": "fighter",

    "Apprenti sorcier": "fighter",
    "Archimage Antonidas": "fighter",
    "Éclat glaciaire": "fighter",
    "Troll des neiges": "fighter",
    "Sindragosa": "fighter",
    "Colosse rocheux": "fighter",
    "Lancier du palais": "fighter",
    "Dragon astral": "fighter",
    "Kodo du désert": "fighter",
    "Kodo de livraison": "fighter",
    "Kodo de pierre": "fighter",
    "Fabriquant d'armure": "fighter",
    "Hacheur nain": "fighter",
    "Explomage gobelin": "fighter",

    "Esprit de l'air": "fighter",
    "Moustique mutant": "fighter",
    "Garuda": "fighter",
    "Satyre du bois sombre": "fighter",
    "Chasseresse vorace": "fighter",
    "Hibou nocturne": "fighter",
    "Élise": "fighter",
    "Élémentaire grondant": "fighter",

    "Automate en bronze": "fighter",
    "Minibot": "fighter",
    "Robot artificié": "fighter",
    "Méca téléporteur": "fighter",
    "Hydre mécanique": "fighter",
    "Rover de sécurité": "fighter",
    "Explomatic": "fighter",

    "Serviteur de Caor": "fighter",
    "Caor, roi des enfers": "fighter",
    "enragé de magma": "fighter",
    "Destrier funeste": "fighter",
    "Garde infernal": "fighter",
    "Homoncule nonchalent": "fighter",
    "Diablotin des abimes": "fighter",
    "Diablotin de service": "fighter",
    "Maitresse succube": "fighter",
    "Seigneur des abimes": "fighter",
    "Pazuzu": "fighter",
    "Mortamor": "fighter",

    "Marcheur du vide": "fighter",
    "Diablotin ardent": "fighter",
    "Démon inférieur": "fighter",
    "Diablotin sournois": "fighter",
    "Diablotin des bois": "fighter",
    "Saccagueur démoniaque": "fighter",
    "Chef de gang des diablotins": "fighter",
    "Invocateur du vide": "fighter",
    "Terreur du vide": "fighter",
    "Dévoreur effroyable": "fighter",
    "Seigneur déchainé des enfers": "fighter",
    "Empereur du vide": "fighter",

    "Pluie de balles": "spell",
    "Sur la planche": "spell",
    "Frappe déferlante": "spell",
    "Corrosion": "spell",
    "Rune contrefaite": "spell",
    "Coup bas": "spell",
    "Sournoiserie": "spell",
    "Métamorphose": "spell",
    "Controle mental": "spell",
    "Poussière temporelle": "spell",
    "Pétrification": "spell",
    "Aspiration d'ame": "spell",
    "Néant": "spell",
    "Marteau divin": "spell",
    "Coup victoire": "spell",
    "Boule de feu": "spell",
    "Fissure": "spell",
    "Colère divine": "spell",
    "Coup de bouclier": "spell",
    "Sortilège de mort": "spell",
    "Engelure": "spell",
    "Salve de flèches": "spell",
    "Coup de tonerre": "spell",
    "Intelligence": "spell",
    "Déflagration": "spell",
    "Concentration": "spell",
    "Fouet de liane": "spell",
    "Floraison": "spell",
    "Fiole explosive": "spell",
    "Régénération": "spell",
    "Écorce": "spell",
    "Surcroissance": "spell",
    "Force de la nature": "spell",
    "Tir reflexe": "spell",
    "Serres de vautour": "spell",
    "Comète": "spell",
    "Nova sacrée": "spell",
    "Sang brulant": "spell",
    "Terrain favorable": "spell",
    "Déchirement": "spell",
    "Lien bestial": "spell",
    "Déplumage": "spell",
    "Instinct du chasseur": "spell",
    "Rugissement sauvage": "spell",
    "Cri de guerre": "spell",
    "Élan des flots": "spell",
    "Mort proche": "spell",
    "Furie sanguinaire": "spell",

}